language: php

php:
    - 5.6
    - 7.0
    - 7.1
    - 7.2

before_script:
    - travis_retry composer self-update
    - travis_retry composer install --no-interaction

script:
    - vendor/phpunit/phpunit/phpunit --testsuite=unit --coverage-html ./build/coverage
